FROM openjdk:14-jdk-alpine

LABEL maintainer = "Henrique Borsatto de Campos<henry_tuori@hotmail.com>"

COPY app app

ENTRYPOINT ["java","-Dlogging.config=app/logback-spring.xml","-cp","app:app/lib/*","br.com.henry.finrule.Application"]
